parameters:
    # rut: true    
    # name: true
    # lastName: false
    # address: true
    # phone: true
    # email: false
    fieldSelected   : ["email", "lastName", "name"]
    fieldColorBackground : ['FF0000']
